baseURL = 'http://nathanclassen.github.io/'
languageCode = 'en-us'
title = 'nhclassen'

[markup.goldmark.renderer]
unsafe= true

[menu]
  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "About"
    url = "/about/"
    weight = -110
# commenting out proceeding items to remove from navigation bar in header
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "Posts"
    url = "/posts/"
    weight = -100
  [[menu.main]]
    identifier = "snippets"
    name = "snippets"
    title = "snippets"
    url = "/snippets/"
    weight = -80
